name: SKY UX Pipeline

on:
  pull_request:
    branches: [
      master
    ]
  push:
    branches: [
      master
    ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install --ignore-scripts
      - run: npm install --no-save blackbaud/skyux-sdk-builder-config
      - run: npx -p @skyux-sdk/cli skyux version
      - run: npx -p @skyux-sdk/cli skyux certs install
      - run: npx -p @skyux-sdk/cli skyux build-public-library
      - run: npx -p @skyux-sdk/cli skyux test --coverage library --headless --platform travis
      - run: bash <(curl -s https://codecov.io/bash)
        if: job.status == 'success'
      - run: npx -p @skyux-sdk/cli skyux e2e --headless --platform travis
