name: SKY UX Pipeline

on:
  pull_request:
    branches: [
      master
    ]
  push:
    branches: [
      master
    ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci --ignore-scripts
      - run: npm i --no-save blackbaud-stevebrush/skyux-sdk-builder-config#debug
      - run: npx -p @skyux-sdk/cli@next skyux certs install

      - name: Run code coverage
        run: npx -p @skyux-sdk/cli@next skyux test --coverage library --platform travis
        env:
          BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
          BROWSER_STACK_PROJECT: ${{ github.repository }}
          TRAVIS_BUILD_NUMBER: ${{ github.run_number }}