name: SKY UX Pipeline

on:
  pull_request:
    branches: [
      master
    ]
  push:
    branches: [
      master
    ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: node:12.16-slim
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @skyux-sdk/cli@next
      - run: skyux version
      - run: skyux certs install
      - run: npm ci --ignore-scripts
      - name: Run code coverage
        uses: ianwalter/bsl@2.1.1
        with:
          args: npm test
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}