name: SKY UX Pipeline

on:
  pull_request:
    branches: [
      master
    ]
  push:
    branches: [
      master
    ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @skyux-sdk/cli@next
      - run: skyux version
      - run: skyux certs install
      - run: npm ci --ignore-scripts
      - run: npm install --no-save blackbaud/skyux-sdk-builder-config
      - name: Run e2e
        run: skyux e2e --platform travis
        env:
          BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
