name: SKY UX Pipeline

on:
  pull_request:
    branches: [
      master
    ]
  push:
    branches: [
      master
    ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm i -g @skyux-sdk/cli@next
      - run: npm ci --ignore-scripts
      - name: Tests
        env:
          BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        run: node ./scripts/ci-test.js
